AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  messenger-webhook-dynamodb

  A sample implementation of an auto responder Messenger bot integrated with Dynamo DB
  

Globals:
  Function:
    Timeout: 3
    CodeUri: messenger/
    Runtime: nodejs12.x
    Environment:
      Variables:
        MESSENGER_VERIFY_TOKEN: !Ref MessengerVerifyToken
        ACCESS_TOKEN: !Ref AccessToken

Parameters:
  MessengerVerifyToken:
    Type: String
  AccessToken:
    Type: String

Resources:
  WebhookVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.webhookVerificationHandler
      Events:
        VerifyWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: get
  ReceiveWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref MessageTable
      Handler: app.receiveWebhookHandler
      Events:
        ReceiveWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
  MessageTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: MessagesTable
      AttributeDefinitions:
        - AttributeName: messageId
          AttributeType: S
      KeySchema:
        - AttributeName: messageId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  VerifyWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Verify Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
  ReceiveWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Receive Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
  WebhookVerificationFunction:
    Description: "Webhook Verification Lambda Function ARN"
    Value: !GetAtt WebhookVerificationFunction.Arn
  ReceiveWebhookFunction:
    Description: "Receive Webhook Lambda Function ARN"
    Value: !GetAtt ReceiveWebhookFunction.Arn
  WebhookVerificationFunctionIamRole:
    Description: "Implicit IAM Role created for Webhook Verification Function function"
    Value: !GetAtt WebhookVerificationFunctionRole.Arn
  ReceiveWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for Receive Webhook Function function"
    Value: !GetAtt ReceiveWebhookFunction.Arn
