AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  messenger-webhook-dynamodb

  Sample SAM Template for messenger-webhook-dynamodb
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    CodeUri: messenger/
    Handler: app.receiveWebhookHandler
    Runtime: nodejs12.x
    Environment:
      Variables:
        MESSENGER_VERIFY_TOKEN: !Ref MessengerVerifyToken
        ACCESS_TOKEN: !Ref AccessToken

Parameters:
  MessengerVerifyToken:
    Type: String
  AccessToken:
    Type: String

Resources:
  WebhookVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        VerifyWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: get
  ReceiveWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ReceiveWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VerifyWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Verify Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ReceiveWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for Receive Webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WebhookVerificationFunction:
    Description: "Webhook Verification Lambda Function ARN"
    Value: !GetAtt WebhookVerificationFunction.Arn
  ReceiveWebhookFunction:
    Description: "Receive Webhook Lambda Function ARN"
    Value: !GetAtt ReceiveWebhookFunction.Arn
  WebhookVerificationFunctionIamRole:
    Description: "Implicit IAM Role created for Webhook Verification Function function"
    Value: !GetAtt WebhookVerificationFunctionRole.Arn
  ReceiveWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for Receive Webhook Function function"
    Value: !GetAtt ReceiveWebhookFunction.Arn
